# Generated by Django 3.2.18 on 2023-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_courseselection_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['course_id']},
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('teacher_id', 'time', 'start', 'end'), name='teacher_time'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('time', 'start', 'end', 'classroom'), name='time_classroom'),
        ),
    ]
