# Generated by Django 3.2.18 on 2023-05-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230516_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
    ]
