# Generated by Django 3.2.18 on 2023-05-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230517_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='remaining_selection',
        ),
    ]
