# Generated by Django 3.2.18 on 2023-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_class_remaining_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='current_selection',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
