# Generated by Django 3.2.18 on 2023-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_class_current_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseselection',
            name='can_drop',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
