# Generated by Django 3.2.18 on 2023-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_courseselection_can_drop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseselection',
            name='can_drop',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
