# Generated by Django 3.2.18 on 2023-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_courseselection_can_drop'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='teacher_time',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('teacher_id', 'time', 'start', 'end', 'semester_id'), name='teacher_time'),
        ),
    ]
