# Generated by Django 3.2.18 on 2023-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20230519_2127'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='time_classroom',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('time', 'start', 'end', 'classroom', 'semester_id'), name='time_classroom'),
        ),
    ]
